### ISSUE TITLE
Problems with special chars (none a-z and normal symbols)

### ISSUE THREAD

**Issue by flamber** [epaulson/star-greader-posts#2]
Hi,

Your script is so wonderful - strange Google hasn't done it, but thank you!

But I seem to have issues with special characters. I got the following error, when running:

Traceback (most recent call last):
  File "star-greader-posts.py", line 88, in <module>
    print "Starring %s  - id %s of feed %s" % (title, id, feedVal)
  File "C:\Python27\lib\encodings\cp850.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode character u'\u2026' in position
 37: character maps to <undefined>

When looking up the \u2026 char it's a three dots (...)

I'm running Python 2.7 on WinXP (Danish).

-hansen

**Comment by epaulson** [comment]
This turned out to be more involved than I had hoped, mostly from setting up a test environment so I could get it to fail :)  I'll keep looking at it and see what I can do. (Apparently the Windows console is especially bad at handling of printing of unicode encodings)

However, I think there's a happy answer in the short term - line 88, that 'print "Starring %s...' is just a debugging line, and you can safely remove it - either comment it out (put a '#' character in front of it) or just delete the line. 

Sorry for basically punting on this. I really ought to do a better job on knowing internationalization
